services:
  web:
    build: ./web
    container_name: web
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./web:/app
      - /app/node_modules
  api-gateway:
    build: ./gateway-service
    env_file:
      - ./gateway-service/.env
    ports:
      - '3001:3001'

  auth-service:
    build: ./auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - '3002:3002'
    depends_on:
      - auth_db
  
  ip-service:
    build: ./ip-service
    env_file:
      - ./ip-service/.env
    ports:
      - 3003:3003
    depends_on:
      - ip_service_db

  log-service:
    build: ./log-service
    env_file:
      - ./log-service/.env
    ports:
      - 9090:9090
    depends_on:
      - log_service_db

  auth_db:
    image: postgres:16.6-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'auth_db'
    ports:
      - '5433:5432'

  ip_service_db:
    image: postgres:16.6-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'ip_service_db'
    ports:
      - '5434:5432'

  log_service_db:
    image: postgres:16.6-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'log_service_db'
    ports:
      - '5435:5432'